### ISSUE TITLE
Problems compiling & using carousel from mofo-ui

### ISSUE THREAD

**Issue by gvn** [mozilla/learning.mozilla.org#2060]
Using branch:  https://github.com/flukeout/learning.mozilla.org/tree/gvn-help

Notes / Repro:
```
rm -rf node_modules
npm i
npm start
```
open: http://localhost:8008/en-US/clubs

in browser:
```
TypeError: _dompurify2.default.sanitize is not a function
   at /Volumes/Nostromo/mozilla-code/learning.mozilla.org/node_modules/mofo-ui/dist/mofo-ui.js:162:126
   at Array.map (native)
   at render (/Volumes/Nostromo/mozilla-code/learning.mozilla.org/node_modules/mofo-ui/dist/mofo-ui.js:154:39)
   at ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (/Volumes/Nostromo/mozilla-code/learning.mozilla.org/node_modules/react/lib/ReactCompositeComponent.js:587:34)
   at ReactCompositeComponentMixin._renderValidatedComponent (/Volumes/Nostromo/mozilla-code/learning.mozilla.org/node_modules/react/lib/ReactCompositeComponent.js:607:32)
   at wrapper [as _renderValidatedComponent] (/Volumes/Nostromo/mozilla-code/learning.mozilla.org/node_modules/react/lib/ReactPerf.js:66:21)
   at ReactCompositeComponentMixin.mountComponent (/Volumes/Nostromo/mozilla-code/learning.mozilla.org/node_modules/react/lib/ReactCompositeComponent.js:220:30)
   at wrapper [as mountComponent] (/Volumes/Nostromo/mozilla-code/learning.mozilla.org/node_modules/react/lib/ReactPerf.js:66:21)
   at Object.ReactReconciler.mountComponent (/Volumes/Nostromo/mozilla-code/learning.mozilla.org/node_modules/react/lib/ReactReconciler.js:37:35)
   at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/Volumes/Nostromo/mozilla-code/learning.mozilla.org/node_modules/react/lib/ReactMultiChild.js:241:44)
```

in /Volumes/Nostromo/mozilla-code/learning.mozilla.org/node_modules/mofo-ui/dist/mofo-ui.js
change line 162 to:

_react2.default.createElement("p", { className: "caption", dangerouslySetInnerHTML: { __html: (item.caption) } }),

control c & `npm start` again

carousel is showing up

doesn't seem like `npm start` is properly watching and rebuilding code within node_modules
it reacts to changes and appears to do something, but hard to say what.

adding console.logs does show up without restarting `npm start`

**Comment by gvn** [comment]
Carousel does work properly in `science`, so I think this is a Webpack configuration issue in Learning.

**Comment by gvn** [comment]
Removing dompurify allows the carousel to work on Learning, but that's not ideal.

**Comment by Pomax** [comment]
hm, worth filing an issue against dompurify to see if they've run into this before, too?
