### ISSUE TITLE
Crash bug when parsing non-json response from wordpress

### ISSUE THREAD

**Issue by cadecairos** [mozilla/learning.mozilla.org#2237]
Someone tried to run a security scan on production, and while thats super uncool (Sorry @gideonthomas, I forgot to resolve the pagerduty incident!), it did uncover a crash bug in the WP content fetching code that causes a crash when the response from the WP API isn't valid JSON.

https://github.com/mozilla/learning.mozilla.org/blob/90b2df7c3bad5741f85970a37004c1f3df30ce93/lib/wp-page-checker.js#L23 

```
2016-09-24T04:35:25.319714+00:00 host app web.2 - /app/node_modules/superagent/lib/node/index.js:691
2016-09-24T04:35:25.319715+00:00 host app web.2 -     return fn(err, res);
2016-09-24T04:35:25.319716+00:00 host app web.2 -            ^
2016-09-24T04:35:25.319748+00:00 host app web.2 - SyntaxError: Unexpected token <
2016-09-24T04:35:25.319749+00:00 host app web.2 -     at Object.parse (native)
2016-09-24T04:35:25.319750+00:00 host app web.2 -     at /app/lib/wp-page-checker.js:23:24
2016-09-24T04:35:25.319751+00:00 host app web.2 -     at Request.callback (/app/node_modules/superagent/lib/node/index.js:691:12)
2016-09-24T04:35:25.319752+00:00 host app web.2 -     at Stream.<anonymous> (/app/node_modules/superagent/lib/node/index.js:922:12)
2016-09-24T04:35:25.319752+00:00 host app web.2 -     at emitNone (events.js:72:20)
2016-09-24T04:35:25.319753+00:00 host app web.2 -     at Stream.emit (events.js:166:7)
2016-09-24T04:35:25.319753+00:00 host app web.2 -     at Unzip.<anonymous> (/app/node_modules/superagent/lib/node/utils.js:108:12)
2016-09-24T04:35:25.319754+00:00 host app web.2 -     at emitNone (events.js:72:20)
2016-09-24T04:35:25.319754+00:00 host app web.2 -     at Unzip.emit (events.js:166:7)
2016-09-24T04:35:25.319755+00:00 host app web.2 -     at endReadableNT (_stream_readable.js:921:12)
2016-09-24T04:35:25.407947+00:00 host heroku web.2 - State changed from up to crashed
```

**Comment by cadecairos** [comment]
hitting this path with a GET request causes a the crash: "/en-US/web-literacy/index.php/contribute/"

**Comment by cadecairos** [comment]
It appears having "index.php" in the slug param of [this query](https://github.com/mozilla/learning.mozilla.org/blob/90b2df7c3bad5741f85970a37004c1f3df30ce93/lib/wp-page-checker.js#L5) causes Wordpress to 302 to their documentation homepage!

**Comment by Pomax** [comment]
that is impressive behaviour on WP's side
