### ISSUE TITLE
npm start failing sometimes

### ISSUE THREAD

**Issue by ScottDowne** [mozilla/learning.mozilla.org#2340]
This feels like a memory issue, and seems like it's happening in the watch from `npm start`

It's happening to me and @cadecairos 

If I directly do a `node app.js` after an `npm install` it seems to work.

When it fails, it's a random syntax error on a random line somewhere in `/build/server.library.js`

This worked for me when I built https://github.com/mozilla/learning.mozilla.org/commit/316c21707967b6bfe70b0175965c70fe91eb7ef1 but if I checkout the PR and run it now, it stills fails.

I got it to run successfully once.

Previously, running the site would fail from time to time, but very infrequently.

@alanmoo @Pomax thoughts?

**Comment by Pomax** [comment]
Do you have STR and maybe a log?

**Comment by ScottDowne** [comment]
STR is run `npm start` it likely isn't going to happen for you, but happens for me and cade, so, linux maybe?

The log seems to be different each time, and fairly random. So I suspect it's a red herring, and a symptom of something else, but I can get you some samples in a bit.

It's a syntax error in `/build/server.library.js` and seems to be because part of the file is missing. like it wasn't finished being built, and just cut off at some point. Seems to happen in watch somewhere. Still feels like a memory issue.

One thing that didn't add up yesterday was why if I went to an older version that I knew worked, it was still broken, yet, broken for Cade. Now I suspect there is an npm package somewhere, maybe a deeper dependency, that's not using a locked down enough version.

**Comment by ScottDowne** [comment]
Some examples:

```
/home/scott/learning.mozilla.org/build/server.library.js:1580
			"become_a_club_captain_link": "Learn more about 
			                              ^^^^^^^^^^^^^^^^^^
SyntaxError: Invalid or unexpected token
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at module.exports (/home/scott/learning.mozilla.org/node_modules/require-uncached/index.js:14:12)
    at FSWatcher.<anonymous> (/home/scott/learning.mozilla.org/app.js:39:20)

```

Another:

```
/home/scott/learning.mozilla.org/build/server.library.js:1749
});
 ^
SyntaxError: Unexpected token )
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at module.exports (/home/scott/learning.mozilla.org/node_modules/require-uncached/index.js:14:12)
    at FSWatcher.<anonymous> (/home/scott/learning.mozilla.org/app.js:39:20)
```
Last one:
```
/home/scott/learning.mozilla.org/build/server.library.js:4768
			"how_become_captain_message": "O processo de candidatura para se tornar um Capitão de Clube incluem 
			                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Invalid or unexpected token
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at module.exports (/home/scott/learning.mozilla.org/node_modules/require-uncached/index.js:14:12)
    at FSWatcher.<anonymous> (/home/scott/learning.mozilla.org/app.js:39:20)

```
I think you get the idea.

**Comment by ScottDowne** [comment]
More digging, because I had a moment.

Fails on this line, as per the error: https://github.com/mozilla/learning.mozilla.org/blob/master/app.js#L39

If I change that to regular require, it works.

**Comment by Pomax** [comment]
let's dig into whether `require-uncached` is doing absolutely the wrong thing on linux

**Comment by Pomax** [comment]
@ScottDowne can you try replacing that line with these two and see what happens?
```
    delete require.cache[require.resolve('./build/server.library')];
    serverBundle = requireUncached('./build/server.library');
```
(intentionally not using a variable for that string, so ensure bundling keeps working)

**Comment by ScottDowne** [comment]
It has a single open issue, lol https://github.com/sindresorhus/require-uncached/issues/2

Dunno if that's a really good sign, or a really bad sign :P

**Comment by ScottDowne** [comment]
Interesting, that fails too.

**Comment by hannahkane** [comment]
@ScottDowne - is this still an issue?

**Comment by ScottDowne** [comment]
More than likely. But I suspect we can just close anyway.

**Comment by aayushsanghavi** [comment]
@ScottDowne @hannahkane I was facing the same issue but as ScottDowne suggested in one of his comments, to use require instead of requireUncached it works.

**Comment by Pomax** [comment]
The require uncached is necessary because plain require does not **re**require the file, which it should be doing. Instead it just gives you a handle for the file it loaded before, so the server never updates when webpack rebuilds the server library, negating the entire point of live server reloading.
